//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: klineprofile
// Function body: klineprofileFunctionMap.cxx

#include    "klineprofileFunctionMap.h"

#include    <XSFunctions/Utilities/XSModelFunction.h>
#include    <XSFunctions/Utilities/XSCall.h>

void 
createklineprofileFunctionMap()
{


	XSModelFunction::addFunctionPointer( "klineprofile", new XSCall<xsccCall>(kerrlineprofile) );

}
