//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: klineprofiles
// Function header: klineprofilesFunctionMap.h

#ifndef    FUNCTIONMAP_H
#define    FUNCTIONMAP_H

#include    <XSFunctions/Utilities/funcType.h>

class    XSCallBase;

void  createklineprofilesFunctionMap();

extern "C"  {


	xsccCall     kline;
	xsccCall     kline5;
	xsccCall     kconv;
	xsccCall     kconv5;
	xsccCall     kconv10;
}


#endif
