//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: klineprofile
// Function header: klineprofileFunctionMap.h

#ifndef    FUNCTIONMAP_H
#define    FUNCTIONMAP_H

#include    <XSFunctions/Utilities/funcType.h>

class    XSCallBase;

void  createklineprofileFunctionMap();

extern "C"  {


	xsccCall     kerrlineprofile;
}


#endif
