name: Bundle

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
    branches:
      - main

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        target: [x86_64-linux-gnu, aarch64-linux-gnu, x86_64-macos-none, aarch64-macos-none]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0-dev.1647+325e0f5f0
      - name: Build and cache
        run: zig build xspec -Doptimize=ReleaseFast -Dtarget=${{matrix.target}}
      - name: Move artifact
        run: mv zig-out/lib/libxsklineprofiles.* ./xspec
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.target}}-lineprofiles
          path: ./xspec

